start: root

root: "(define-fun" "inv" "((" "s" "(BitVec" "4))" "(" "t" "(BitVec" "4))" "))" "(BitVec" "4)" expr ")"

?expr: "s"
     | "t"
     | "#x0" | "#x8" | "#x7"
     | "(" "bvneg"  expr ")"
     | "(" "bvnot"  expr ")"
     | "(" "bvadd"  expr expr ")"
     | "(" "bvsub"  expr expr ")"
     | "(" "bvand"  expr expr ")"
     | "(" "bvlshr" expr expr ")"
     | "(" "bvor"   expr expr ")"
     | "(" "bvshl"  expr expr ")"

%import common.WS
%ignore WS
